fix(main) unused function in libprintf

diff --git a/my_printf/Makefile b/my_printf/Makefile
--- a/my_printf/Makefile
+++ b/my_printf/Makefile
@@ -29,14 +29,14 @@ all:	$(NAME)
 
 $(NAME):	$(OBJ)
 	@ar rcs $(NAME) $(OBJ)\
-	&& echo "\033[1;32m[SUCCES]\033[0m" $(NAME)\
-	|| echo "\033[1;31m[ERROR]\033[0m" $(NAME)
+	&& echo -e "\033[1;32m[SUCCES]\033[0m" $(NAME)\
+	|| echo -e "\033[1;31m[ERROR]\033[0m" $(NAME)
 
 $(BUILD_DIR)/%.o:	%.c
 	@mkdir -p $(dir $@)
 	@gcc -c -o $@ $< $(CFLAGS) $(WFLAGS)\
-	&& echo "\033[1;32m[OK]\033[0m" $<\
-	|| echo "\033[1;31m[KO]\033[0m" $<
+	&& echo -e "\033[1;32m[OK]\033[0m" $<\
+	|| echo -e "\033[1;31m[KO]\033[0m" $<
 
 debug:	CFLAGS += -g
 debug:	re
@@ -45,33 +45,33 @@ clean:
 	@for file in $(BUILD_DIR)/*; do\
 		if [ -d $$file ]; then\
 			rm -rf $$file;\
-			echo "\033[1;31m[DELETED]\033[0m" $$file;\
+			echo -e "\033[1;31m[DELETED]\033[0m" $$file;\
 		fi;\
 	done
-	@echo "\033[1;31m[CLEAN]\033[0m" $(PROJECT_NAME)
+	@echo -e "\033[1;31m[CLEAN]\033[0m" $(PROJECT_NAME)
 	@rm -f $(shell find -name '*.gc*' -type f)
 
 fclean: clean
 	@rm -f $(TEST_NAME)
-	@echo "\033[1;31m[DELETED]\033[0m" $(TEST_NAME)
+	@echo -e "\033[1;31m[DELETED]\033[0m" $(TEST_NAME)
 	@rm -rf $(BUILD_DIR)
-	@echo "\033[1;31m[DELETED]\033[0m" $(BUILD_DIR)
+	@echo -e "\033[1;31m[DELETED]\033[0m" $(BUILD_DIR)
 	@rm -f $(NAME)
-	@echo "\033[1;31m[DELETED]\033[0m" $(NAME)
+	@echo -e "\033[1;31m[DELETED]\033[0m" $(NAME)
 
 re:	fclean all
 
 tests_run:	CFLAGS += -lcriterion --coverage
 tests_run:	fclean
 	@if [ ! -d "tests" ]; then\
-		echo "\033[1;31m[ERROR]\033[0m" "No tests directory";\
+		echo -e "\033[1;31m[ERROR]\033[0m" "No tests directory";\
 		exit 1;\
 	fi
 	@mkdir -p $(BUILD_DIR)
 	@mkdir -p $(BUILD_TESTS_DIR)
 	@gcc -o $(TEST_NAME) $(TEST_SRC) $(SRC) $(CFLAGS) $(WFLAGS) $(CRITERION)\
-	&& echo "\033[1;32m[OK]\033[0m" $(TEST_NAME)\
-	|| echo "\033[1;31m[KO]\033[0m" $(TEST_NAME)
+	&& echo -e "\033[1;32m[OK]\033[0m" $(TEST_NAME)\
+	|| echo -e "\033[1;31m[KO]\033[0m" $(TEST_NAME)
 	@./$(TEST_NAME)
 	mv *.gc* $(BUILD_TESTS_DIR)
 	gcovr --exclude tests/
@@ -81,4 +81,4 @@ tests_run:	fclean
 .SILENT: all clean fclean re debug tests_run
 
 %:
-	@echo "\033[1;31m[ERROR]\033[0m" "No rule to make target '$@'"
+	@echo -e "\033[1;31m[ERROR]\033[0m" "No rule to make target '$@'"
